# Generated by Django 4.1.2 on 2023-08-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('roll', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField()),
                ('mob', models.IntegerField()),
            ],
        ),
    ]
